### ISSUE TITLE
no response on terminal about ansible

### ISSUE THREAD

**Issue by cjd9023** [DoclerLabs/openstack#16]
i follow these steps  , but no output about ansible
$ cd openstack/openstack-installer
$ scripts/restorecfg.sh aio
$ scripts/generate_secrets.py
$ cd vagrant
$ vagrant up
---
[root@onecomputer-04 openstack-installer]# scripts/restorecfg.sh aio
[root@onecomputer-04 openstack-installer]# 
[root@onecomputer-04 openstack-installer]# scripts/generate_secrets.py
[root@onecomputer-04 openstack-installer]# 
[root@onecomputer-04 openstack-installer]# cd vagrant
[root@onecomputer-04 vagrant]# vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set forwarded ports...
==> default: Fixed port collision for 22 => 2222. Now on port 2205.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
    default: Adapter 3: hostonly
    default: Adapter 4: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2205 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2205
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
[default] GuestAdditions 5.1.14 running --- OK.
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => /root/openstack/openstack-installer/vagrant
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
[root@onecomputer-04 vagrant]#
[root@onecomputer-04 vagrant]# ansible --version
ansible 2.2.1.0
  config file = /root/openstack/openstack-installer/vagrant/ansible.cfg
  configured module search path = Default w/o overrides

after i vagrant box add  command to import  bento/ubuntu_16.04 box ,
i run  vagrant up,  less than 1 min to finish  ,so quick.

how can i fix this ?

thanks for answer.

**Comment by gyurco** [comment]
default: Machine already provisioned.
.
.
==> default: Fixed port collision for 22 => 2222. Now on port 2205

Seems you already have a vagrant machine running (or just started it, and didn't stop)? Try 'vagrant destroy' first.

**Comment by cjd9023** [comment]
@gyurco  thanks ,i destroy ,and up again ,it work fine, and i need set http_proxy on my Vagrant file to install 
 software.  
vagrant plugin install vagrant-proxyconf
Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.hostname = "openstack-aio"
  config.proxy.http = "http://x.x.x.x:9999"
  config.proxy.https = "http://x.x.x.x:9999"
  config.proxy.no_proxy = "localhost,127.0.0.1"
