### ISSUE TITLE
error on TASK [os_keystone_service : get an admin token]

### ISSUE THREAD

**Issue by cjd9023** [DoclerLabs/openstack#17]
i try 3 times but same error .
TASK [os_keystone_service : get an admin token] ********************************
task path: /root/openstack/openstack-installer/roles/os_keystone_service/tasks/main.yml:15
Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/cloud/openstack/os_auth.py
<10.10.0.11> ESTABLISH SSH CONNECTION FOR USER: vagrant
<10.10.0.11> SSH: EXEC ssh -vvv -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -i /root/openstack/openstack-installer/vagrant/.vagrant/machines/default/virtualbox/private_key -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=30 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r 10.10.0.11 '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
fatal: [openstack-aio]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_name": "os_auth"
    }, 
    "module_stderr": "OpenSSH_6.6.1, OpenSSL 1.0.1e-fips 11 Feb 2013\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 18610\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\nWARNING:keystoneauth.identity.generic.base:Discovering versions from the identity service failed when creating the password plugin. Attempting to determine version from URL.\nTraceback (most recent call last):\n  File \"/tmp/ansible_1QQ_1E/ansible_module_os_auth.py\", line 69, in <module>\n    main()\n  File \"/tmp/ansible_1QQ_1E/ansible_module_os_auth.py\", line 60, in main\n    auth_token=cloud.auth_token,\n  File \"/usr/lib/python2.7/dist-packages/shade/openstackcloud.py\", line 339, in auth_token\n    return self.keystone_session.get_token()\n  File \"/usr/lib/python2.7/dist-packages/keystoneauth1/session.py\", line 749, in get_token\n    return (self.get_auth_headers(auth) or {}).get('X-Auth-Token')\n  File \"/usr/lib/python2.7/dist-packages/keystoneauth1/session.py\", line 727, in get_auth_headers\n    return auth.get_headers(self, **kwargs)\n  File \"/usr/lib/python2.7/dist-packages/keystoneauth1/plugin.py\", line 90, in get_headers\n    token = self.get_token(session)\n  File \"/usr/lib/python2.7/dist-packages/keystoneauth1/identity/base.py\", line 90, in get_token\n    return self.get_access(session).auth_token\n  File \"/usr/lib/python2.7/dist-packages/keystoneauth1/identity/base.py\", line 136, in get_access\n    self.auth_ref = self.get_auth_ref(session)\n  File \"/usr/lib/python2.7/dist-packages/keystoneauth1/identity/generic/base.py\", line 181, in get_auth_ref\n    return self._plugin.get_auth_ref(session, **kwargs)\n  File \"/usr/lib/python2.7/dist-packages/keystoneauth1/identity/v3/base.py\", line 167, in get_auth_ref\n    authenticated=False, log=False, **rkwargs)\n  File \"/usr/lib/python2.7/dist-packages/keystoneauth1/session.py\", line 675, in post\n    return self.request(url, 'POST', **kwargs)\n  File \"/usr/lib/python2.7/dist-packages/positional/__init__.py\", line 101, in inner\n    return wrapped(*args, **kwargs)\n  File \"/usr/lib/python2.7/dist-packages/keystoneauth1/session.py\", line 570, in request\n    raise exceptions.from_response(resp, method, url)\nkeystoneauth1.exceptions.http.ServiceUnavailable: Service Unavailable (HTTP 503)\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE"
}

--- Vagrant file
[root@onecomputer-04 vagrant]# cat Vagrantfile 
# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
echo "auto enp0s10" > /etc/network/interfaces.d/enp0s10.cfg
echo "iface enp0s10 inet manual" >> /etc/network/interfaces.d/enp0s10.cfg
ifup enp0s10
SCRIPT

Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.hostname = "openstack-aio"
  config.proxy.http = "http://10.202.91.52:3128"
  config.proxy.https = "http://10.202.91.52:3128"
  config.proxy.no_proxy = "localhost,127.0.0.1,10.10.0.11,10.10.1.11,10.10.2.11,10.10.0.10,10.10.1.10,10.10.2.10,10.10.1.254,10.10.0.0"
  # Networking
  config.vm.network :private_network, ip: "10.10.0.11"  # management
  config.vm.network :private_network, ip: "10.10.1.11"  # external
  config.vm.network :private_network, ip: "10.10.2.11", # Neutron flat network
                     auto_config: false

  config.vm.provider :virtualbox do |vb|
    vb.cpus = 4
    vb.memory = "12288"
    vb.customize ["modifyvm", :id, "--nicpromisc4", "allow-all"]
  end

  config.vm.provision "shell", inline: $script

  config.vm.provision :ansible do |ansible|
    ansible.inventory_path = "../inventory/inventory.py"
    ansible.limit = "all"
    ansible.playbook = "../aio-deploy.yml"
    ansible.verbose = "vvvv"
  end
end

**Comment by cjd9023** [comment]
i fix this error, my  network environment need  proxy to  download software.
and i add below line to  Vagrant file,  to avoid keystone  use  haproxy connect to endpoint , no more 503 service unavailable.
config.proxy.no_proxy = "localhost,127.0.0.1,10.10.0.11,10.10.1.11,10.10.2.11,10.10.0.10,10.10.1.10,10.10.2.10,10.10.0.254,10.10.1.254"

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
openstack-aio              : ok=895  changed=584  unreachable=0    failed=0   

thanks

**Comment by gyurco** [comment]
Great, so it is not really the problem of the installer. Btw, if you need a proxy for apt, I suggest to configure it with adding:
````
Acquire::http::Proxy "http://your.proxy.here:port/";
````
to a file in /etc/apt/apt.conf.d

**Comment by andruwa13** [comment]
@gyurco  hi, not work (TASK [os_keystone_service : get an admin token])
Ubuntu 18.04.3 LTS
4.15.0-60-generic
git branch master

`fatal: [openstack-aio]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "api_timeout": null, 
            "auth": {
                "auth_url": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "domain-name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "project_domain_name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "project_name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            }, 
            "auth_type": null, 
            "availability_zone": null, 
            "ca_cert": "", 
            "cacert": "", 
            "client_cert": null, 
            "client_key": null, 
            "cloud": null, 
            "interface": "public", 
            "region_name": "RegionONE", 
            "timeout": 180, 
            "validate_certs": true, 
            "wait": true
        }
    }, 
    "msg": "To utilize this module, the installed version ofthe openstacksdk library MUST be >=0.12.0"
}
`

**Comment by gyurco** [comment]
Please read the error message:

To utilize this module, the installed version ofthe openstacksdk library MUST be >=0.12.0

This comes from the ansible module, check this library version on your host system.
