### ISSUE TITLE
Deploying to Baremetal

### ISSUE THREAD

**Issue by JImmyGriffinNIAID** [DoclerLabs/openstack#20]
Hello, 

This isn't really a issue, I wanted to know if you have instructions for deploying to baremetal? I'm working on a school project and have 7 nodes which all can be used for compute and 4 compute/storage. Any guidance would be appreciated. 

Thanks

Jimmy

**Comment by gyurco** [comment]
Is this doesn't help?

https://github.com/DoclerLabs/openstack/blob/master/openstack-installer/docs/installation.rst

Installation of the host OS is not covered by this installer, since you have many good options to do it (personally I'm using MAAS - https://maas.io/).
